spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/woojoo?useUnicode=true&characterEncoding=utf
    username: leui
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

file:
  path: /Users/leui/Desktop/Leui/Workspace/woojoo-image/

jwt:
  password: testpassword1234

project:
  properties:
    firebase-create-scoped: "https://www.googleapis.com/auth/firebase.messaging"

sms:
  serviceId: ncp:sms:kr:305396449835:woojoo
  accessKey: ULnSErxzd1AYoGao2wzX
  secretKey: noHGrMlhhf7JER9e1nZtLWeRXownAw5qMqysa0cd

