spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/woojoo?useUnicode=true&characterEncoding=utf
    username: leui
    password: 1234
#    url: jdbc:h2:~/local
#    driverClassName: org.h2.Driver
#    username: sa
#    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

file:
  path: /Users/leui/Desktop/Leui/Workspace/woojoo-image/


jwt:
  header: Authorization
  password: testpassword1234
  token-validity-in-seconds: 86400


